export default {
	content: {
		SetsReps:
			'The program I’m creating will have numbers for how many repetitions you should complete in a set, and how many sets to do at once. These are suggestions, and your needs will change as you progress. In general, if an exercise is aimed at strengthening an area I want you to feel fatigued by the end of each set and perform about 3 of those sets at a time (with a small 60 second rest between sets). You can increase challenge by adding reps, adding weight, increasing resistance of the band, etc. Think of the variables involved and increase one until the challenge feels appropriate. You should never have your symptoms increase during these exercises. If they do, lower one of the variables and try again. One kind of pain that is OK to feel is ‘delayed onset muscle soreness’ or DOMS. This usually manifests the day after new exercises and is often described as a deep ache that hurts when you try to use the muscle that was worked out the previous day. While I don’t want this to be debilitating, feeling this is a good sign and I’m fine with it ☺.',
		MotorControl:
			'One aspect of rehab we are working on is your ‘motor control’. This refers to your brain’s ability to control your muscles appropriately given certain demands. For these exercises higher repetitions and lower loads are recommended. Building motor control takes lots of input so the more you can complete the movement the more reminders the brain receives about how to properly coordinate those muscles.',
		IceVsHeat:
			'While theoretically ice has an anti-inflammatory effect and heat has a pro-inflammatory effect, realistically it is unlikely that the temperature will penetrate deep enough to effect the exact site of your injury unless it is very superficial. As a result, you can use whatever feels best for you. What both of these modalities do is confuse your brain by mixing up the current sensory input with new temperature input. The brain is not sure what to pay attention to and it can reduce the feeling of pain.',
		SymptomLog:
			'Attached to this email is a template for a symptom log. Its purpose is to help you keep track of what activities aggravate or help your symptoms. It also helps you keep track of things over time which will help us track progress. This log really is crucial – it provides essential information and takes out some of the highly subjective feelings that often surround rehab. For the pain scale, 10 = take me to the hospital immediately while 0 = nothing.',
		ActivityModification:
			'In general, rehab is not a great time to learn new skills or try new tricks. If you have an activity you love doing and it does not actively make your symptoms worse, feel free to continue that activity. If you have questions about specific activities that you are unsure are appropriate feel free to ask! Rehab often requires us to be intelligent in our choices, but that doesn’t mean you have to stop everything you love doing.',
		NextStepsEVAL:
			'Stay in touch about how things progress over the next week. You can contact me any time with any questions – feel free to email videos or pictures if you’re not sure you are doing an exercise correctly. Things often change rapidly at the beginning of rehab and I can make some changes easily by email. Depending on how you’re feeling another session might be beneficial to lock in a longer-term program for you.',
		NextStepsFollowUp:
			'Stay in touch about how things progress over the next week. We are refining your program and my goal is to help you create a routine that supports your long-term goals.'
	}
};
